<?php return array (
  'btn' => '#ff4f02',
  'btn_text' => '#ffffff',
  'bg_page' => '#dddddd',
  'text_top' => '#ffffff',
  'link_top' => '#ff4f02',
  'bg_top' => '',
  'text_head' => '#ffffff',
  'link_head' => '#ff4f02',
  'bg_header' => '#ff4f02',
  'text' => '#444444',
  'link' => '#f08e3e',
  'bg_body' => '#ffffff',
  'text_foot' => '#444444',
  'link_foot' => '#f08e3e',
  'bg_footer' => '#ededed',
  'text_bottom' => '#ffffff',
  'link_bottom' => '#f08e3e',
  'bg_bottom' => '',
);